[package]
name = "mrx-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
mrx-macros-cli = { path = "../macros/cli" }
ignore = "0.4.25"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.146"
tempfile = "3.23.0"
thiserror = "2.0.17"
toml = "0.9.8"
rnix = "0.12.0"
