[package]
name = "mrx-build"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
mrx-macros-cli = { path = "../macros/cli" }
mrx-utils = { path = "../mrx-utils" }
serde = { version = "1.0.228" }
serde_json = "1.0.146"
thiserror = "2.0.17"
