[package]
name = "mrx-build"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
mrx-generate = { path = "../mrx-generate" }
mrx-hook = { path = "../mrx-hook" }
mrx-utils = { path = "../mrx-utils" }
thiserror = "2.0.17"

[lints]
workspace = true
